name = "Polymania"
author = "Patbox"
version = "<MODPACKVERSION>"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "58d25b539a80f2750d7e3b4db4206b5889aa3c20c3ace9bc276083b408836fe9"

[versions]
fabric = "0.16.7"
minecraft = "1.21.3"

[options]
acceptable-game-versions = ["1.21.3", "1.21.2"]
datapack-folder = "resources/common/required"
