name = "Polymania"
author = "Patbox"
version = "<MODPACKVERSION>"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b504fdf30c0ac08d1848caeb8062b84223c6b08e27bc407a0c98e989baeac5b9"

[versions]
fabric = "0.16.7"
minecraft = "1.21.3"

[options]
acceptable-game-versions = ["1.21.3", "1.21.2"]
datapack-folder = "resources/common/required"
